USE phpProject;INSERT INTO subject (name, hrs) VALUES ("algorithmique et programmation (S1)", "11")
,("atelier de l'informaticien (S1)", "13")
,("introduction au raisonnement mathématiques (S1)", "6")
,("suites et fonctions réelles (S1)", "20")
,("arithmétique dans Z (S1)", "11")
,("anglais (S1)", "13")
,("algorithmique et programmation (S2)", "16")
,("modélisation (S2)", "10")
,("outils mathématiques pour l'informatique (S2)", "22")
,("mathématiques (S2)", "13")
,("analyse (S2)", "24")
,("algèbre (S2)", "21")
,("projet informatique (S2)", "22")
,("projet personnel et professionnel (S2)", "9")
,("préparation au C2I (S2)", "12")
,("Anglais (S2)", "17")
,("algorithmique et programmation (S3)", "10")
,("atelier de l'informaticien (S3)", "19")
,("architecture des ordinateurs (S3)", "11")
,("bases de données et Internet (S3)", "12")
,("applications de l'algèbre (S3)", "23")
,("analyse (S3)", "15")
,("algèbre (S3)", "17")
,("mathématiques numériques (S3)", "10")
,("anglais (S3)", "18")
,("unité d'enseignement libre (S3)", "7")
,("programmation fonctionnelle (S4)", "19")
,("algorithmique et combinatoire des structures discrètes (S4)", "18")
,("programmation impérative (S4)", "7")
,("probabilité discrète (S4)", "7")
,("suites et séries de fontion (S4)", "17")
,("projet informatique (S4)", "18")
,("bases du système comptable (S4)", "10")
,("anglais (S4)", "24")
,("mise à niveau informatique (S5)", "15")
,("réseaux (S5)", "13")
,("analyse des algorithmes (S5)", "8")
,("programmation avancée et structures de données (S5)", "23")
,("systèmes d'information (S5)", "16")
,("analyse et conception des systèmes d'information (S5)", "16")
,("programmation linéaire (S5)", "6")
,("logique (S5)", "16")
,("topologie des espaces métriques (S5)", "7")
,("analyse numérique matricielle (S5)", "11")
,("recherche opérationnelle (S5)", "13")
,("statistiques (S5)", "20")
,("projet informatique (S5)", "23")
,("projet personnel et professionnel (S5)", "15")
,("gestion comptable (S5)", "13")
,("anglais (S5)", "15")
,("techniques de communication (S5)", "14")
,("renforcement programmation orientée objets Java (S6)", "18")
,("génie logiciel (S6)", "7")
,("génie logiciel (S6)", "17")
,("bases de données (S6)", "10")
,("programmation des systèmes d'information (S6)", "15")
,("théorie des langages (S6)", "21")
,("calcul différentiel et optimisation (S6)", "8")
,("outils numériques (S6)", "12")
,("projet informatique INGÉ (S6)", "9")
,("projet informatique MI (S6)", "8")
,("projet informatique MIAGE (S6)", "11")
,("stage ou projet de fin d'études (S6)", "7")
,("droit (S6)", "14")
,("environnement économique de l'entreprise (S6)", "8")
,("anglais (S6)", "11")
;
