USE phpProject; 
INSERT INTO teacher (name, salary) VALUES 
("Jean  DUMAS", 28)
,("Marie  ROY", 22)
,("Michel  BRUN", 25)
,("Monique  GUILLOU", 29)
,("Claude  JEAN", 19)
,("André  LEGER", 21)
,("Pierre  GAY", 19)
,("Jacques  BERGER", 29)
,("Bernard  MARIE", 29)
,("Nicole  ROGER", 18)
,("Jacqueline  GOFF", 29)
,("Gérard  MOREL", 28)
,("Daniel  DUVAL", 28)
,("René  GUILLAUME", 18)
,("Robert  FABRE", 25)
,("Françoise  DUMONT", 23)
,("Christiane  BRUN", 29)
,("Guy  LEGRAND", 29)
,("Roger  BERGER", 16)
;
