USE phpProject; 
INSERT INTO teacher (name) VALUES 
("Jean  LEROY")
,("Marie  CARRE")
,("Michel  BARON")
,("Monique  PREVOST")
,("Claude  LECLERC")
,("André  PETIT")
,("Pierre  CHEVALIER")
,("Jacques  DAVID")
,("Bernard  BRIAND")
,("Nicole  CARON")
,("Jacqueline  DUBOIS")
,("Gérard  COLIN")
,("Daniel  COLIN")
,("René  THOMAS")
,("Robert  BAILLY")
,("Françoise  LAMBERT")
,("Christiane  MORIN")
,("Guy  CHARPENTIER")
,("Roger  ANDRE")
;
